---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile
    repo: registry.itdog.me/acme-sh
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

##---
##kind: pipeline
##type: docker
##name: linux-arm64
##
##platform:
##  arch: arm64
##  os: linux
##
##steps:
##- name: publish
##  image: plugins/docker:18
##  settings:
##    auto_tag: true
##    auto_tag_suffix: linux-amd64
##    dockerfile: Dockerfile
##    repo: registry.itdog.me/acme-sh
##    username:
##      from_secret: docker_username
##    password:
##      from_secret: docker_password
##
##trigger:
##  event:
##  - push
##  - tag
#
#depends_on:
#- linux-amd64
#
---
kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile
    repo: registry.itdog.me/acme-sh
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
  - push
  - tag

depends_on:
- linux-amd64

---
kind: pipeline
type: docker
name: manifest

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    auto_tag: true
    ignore_missing: true
    spec: ci/manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
  - push
  - tag

depends_on:
#- linux-arm64
- linux-arm
