kind: pipeline
type: docker
name: build-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build-by-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.itdog.me
      repo: registry.itdog.me/ting/docker-acme.sh
      tags:
        - ${DRONE_BRANCH}-${DRONE_STAGE_ARCH}
    when:
      event:
      - push

  - name: build-by-tag
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.itdog.me
      repo: registry.itdog.me/ting/docker-acme.sh
      tags:
        - ${DRONE_TAG}-${DRONE_STAGE_ARCH}
    when:
      event:
      - tag

trigger:
  event:
  - push
  - tag

---
kind: pipeline
type: docker
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build-by-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.itdog.me
      repo: registry.itdog.me/ting/docker-acme.sh
      tags:
        - ${DRONE_BRANCH}-${DRONE_STAGE_ARCH}
    when:
      event:
      - push

  - name: build-by-tag
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.itdog.me
      repo: registry.itdog.me/ting/docker-acme.sh
      tags:
        - ${DRONE_TAG}-${DRONE_STAGE_ARCH}
    when:
      event:
      - tag

trigger:
  event:
  - push
  - tag

---
kind: pipeline
type: docker
name: package-with-manifest

steps:
  - name: manifest-by-tag
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: registry.itdog.me/ting/docker-acme.sh:${DRONE_TAG:=none}
      template: registry.itdog.me/ting/docker-acme.sh:${DRONE_TAG:=none}-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      event:
        - tag

  - name: manifest-by-tag-latest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: registry.itdog.me/ting/docker-acme.sh:latest
      template: registry.itdog.me/ting/docker-acme.sh:${DRONE_TAG:=none}-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      event:
        - tag

  - name: manifest-by-push
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: registry.itdog.me/ting/docker-acme.sh:${DRONE_BRANCH:=none}
      template: registry.itdog.me/ting/docker-acme.sh:${DRONE_BRANCH:=none}-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      event:
        - push

  - name: telegram-notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_notification_bot_token
      to:
        from_secret: telegram_notification_receiver
      format: markdown

trigger:
  event:
    - tag
    - push

depends_on:
  - build-amd64
  - build-arm64
